/**
 * Expense Integration Engine
 * Maps purchases / payroll / fixed-costs → expense_transactions automatically.
 * Does NOT modify any existing route logic — only adds accounting entries.
 */
import { db } from "@workspace/db";
import { expenseTransactionsTable } from "@workspace/db/schema";
import { and, eq } from "drizzle-orm";

function fmt(v: number) { return String(v.toFixed(2)); }
function toNum(v: unknown) { return parseFloat(String(v)) || 0; }

// ─── Purchase category → expense code ────────────────────────────────────────
// All non-food purchases are operating expenses.
// Food/beverages are COGS but we still create an accounting mirror.
const PURCHASE_CATEGORY_MAP: Record<string, string> = {
  // Purchase auto-mirror codes — mapped to the 7-main hospitality tree.
  // (food/beverage/meat/… mirrors live in the ledger as isAutoGenerated=true
  // and are EXCLUDED from the P&L; we still map them to a valid live code.)
  food:          "5-4-8",   // Kitchen Consumables
  beverages:     "5-4-8",
  meat:          "5-4-8",
  chicken:       "5-4-8",
  fish:          "5-4-8",
  vegetables:    "5-4-8",
  dairy:         "5-4-8",
  bakery:        "5-4-8",
  cleaning:      "5-4-6",   // Cleaning Materials
  packaging:     "5-4-5",   // Packaging
  maintenance:   "5-6-1",   // Equipment Maintenance
  fuel:          "5-4-4",   // Fuel
  electricity:   "5-4-1",   // Electricity
  water:         "5-4-2",   // Water
  gas:           "5-4-3",   // Gas
  telecom:       "5-7-4",   // Communication Expenses
  marketing:     "5-5-1",   // Social Media Ads
  it:            "5-3-3",   // Software Subscriptions
  stationery:    "5-7-2",   // Stationery
  transport:     "5-4-10",  // Delivery Expenses
  rent:          "5-3-1",   // Rent
  others:        "5-7-1",   // Office Supplies (generic admin fallback)
  other:         "5-7-1",
};

export function mapPurchaseCategoryToExpenseCode(category: string): string {
  return PURCHASE_CATEGORY_MAP[category?.toLowerCase()] ?? "5-7-1";
}

// ─── Fixed-cost template category → expense code ──────────────────────────────
const FIXED_COST_CATEGORY_MAP: Record<string, string> = {
  "staff-salaries":    "5-1-1",   // Salaries & Wages
  "owner-drawings":    "5-7-1",   // Office Supplies (admin fallback)
  "apps-subscriptions":"5-3-3",   // Software Subscriptions
  "rent":              "5-3-1",   // Rent (Fixed Operating)
  "utilities":         "5-4-1",   // Electricity (Variable Operating)
  "other-fixed":       "5-3-4",   // Insurance (Fixed Operating fallback)
};

export function mapFixedCostCategoryToExpenseCode(category: string): string {
  return FIXED_COST_CATEGORY_MAP[category] ?? "5-3-4";
}

// ─── Source ID helpers ────────────────────────────────────────────────────────
export const sourceId = {
  purchase:   (purchaseId: number) => `purchase:${purchaseId}`,
  payroll:    (restaurantId: number, month: string, employeeId: number) => `payroll:${restaurantId}:${month}:${employeeId}`,
  fixedCost:  (restaurantId: number, month: string, templateId: number) => `fixed:${restaurantId}:${month}:${templateId}`,
};

// ─── Core upsert helper ───────────────────────────────────────────────────────
async function upsertExpense(params: {
  restaurantId:   number;
  date:           string;
  categoryCode:   string;
  description:    string;
  net:            number;
  vatAmount:      number;
  isVatApplicable:boolean;
  costCenter?:    string;
  referenceNo?:   string;
  notes?:         string;
  sourceType:     string;
  srcId:          string;
}) {
  const { restaurantId, date, categoryCode, description, net, vatAmount, isVatApplicable,
          costCenter, referenceNo, notes, sourceType, srcId } = params;
  const month   = date.substring(0, 7);
  const total   = +(net + vatAmount).toFixed(2);
  const vatRate = isVatApplicable ? "15.00" : "0.00";

  // Check if entry already exists for this source
  const existing = await db.select({ id: expenseTransactionsTable.id })
    .from(expenseTransactionsTable)
    .where(and(
      eq(expenseTransactionsTable.restaurantId, restaurantId),
      eq(expenseTransactionsTable.sourceId, srcId),
    ));

  const values = {
    restaurantId,
    date,
    month,
    categoryCode,
    description,
    amount:          fmt(net),
    isVatApplicable,
    vatRate,
    vatAmount:       fmt(vatAmount),
    totalAmount:     fmt(total),
    costCenter:      costCenter ?? null,
    referenceNo:     referenceNo ?? null,
    notes:           notes ?? null,
    sourceType,
    sourceId:        srcId,
    isAutoGenerated: true,
    updatedAt:       new Date(),
  };

  if (existing.length > 0) {
    await db.update(expenseTransactionsTable).set(values)
      .where(eq(expenseTransactionsTable.id, existing[0].id));
  } else {
    await db.insert(expenseTransactionsTable).values(values);
  }
}

// ─── Delete expense entry by sourceId ────────────────────────────────────────
export async function deleteExpenseBySourceId(restaurantId: number, srcId: string) {
  await db.delete(expenseTransactionsTable).where(
    and(
      eq(expenseTransactionsTable.restaurantId, restaurantId),
      eq(expenseTransactionsTable.sourceId, srcId),
    )
  );
}

// ─── Purchase → Expense ───────────────────────────────────────────────────────
export async function upsertExpenseFromPurchase(restaurantId: number, purchase: {
  id:              number;
  date:            string;
  productName:     string;
  supplierName:    string;
  category:        string;
  amountBeforeVat: number;
  vatAmount:       number;
  invoiceType:     string;
  invoiceId?:      string;
}) {
  const categoryCode   = mapPurchaseCategoryToExpenseCode(purchase.category);
  const isVat          = purchase.invoiceType !== "non-tax" && purchase.vatAmount > 0;
  const descr          = purchase.supplierName
    ? `${purchase.productName} (${purchase.supplierName})`
    : purchase.productName;

  await upsertExpense({
    restaurantId,
    date:           purchase.date,
    categoryCode,
    description:    descr,
    net:            purchase.amountBeforeVat,
    vatAmount:      purchase.vatAmount,
    isVatApplicable:isVat,
    referenceNo:    purchase.invoiceId,
    notes:          `مشتريات — ${purchase.category}`,
    sourceType:     "purchase",
    srcId:          sourceId.purchase(purchase.id),
  });
}

// ─── Single Employee Payroll → Expense ───────────────────────────────────────
export async function upsertExpenseFromEmployee(restaurantId: number, month: string, employee: {
  id:     number;
  name:   string;
  salary: number;
  overtime: number;
  deductions: number;
  absences: number;
}) {
  const net  = Math.max(0, employee.salary + employee.overtime - employee.deductions - employee.absences);
  const date = `${month}-01`;
  await upsertExpense({
    restaurantId,
    date,
    categoryCode:    "5-1-1",   // Salaries & Wages (HR & Employee Costs)
    description:     `راتب — ${employee.name}`,
    net,
    vatAmount:       0,
    isVatApplicable: false,
    costCenter:      "Payroll",
    notes:           `رواتب ${month}`,
    sourceType:      "payroll",
    srcId:           sourceId.payroll(restaurantId, month, employee.id),
  });
}

// ─── Fixed-cost Template → Expense ───────────────────────────────────────────
export async function upsertExpenseFromFixedCost(restaurantId: number, month: string, template: {
  id:       number;
  category: string;
  name:     string;
  amount:   number;
}) {
  const categoryCode = mapFixedCostCategoryToExpenseCode(template.category);
  const date         = `${month}-01`;
  await upsertExpense({
    restaurantId,
    date,
    categoryCode,
    description:     template.name,
    net:             template.amount,
    vatAmount:       0,
    isVatApplicable: false,
    costCenter:      "Fixed Costs",
    notes:           `مصروفات ثابتة ${month}`,
    sourceType:      "fixed-cost",
    srcId:           sourceId.fixedCost(restaurantId, month, template.id),
  });
}
