/**
 * Unified VAT Engine — single source of truth for ALL VAT calculations.
 *
 * Every endpoint that surfaces VAT (vat.ts, reports.ts P&L, dashboard.ts,
 * diagnostics.ts, financial summary, expense / purchase reports) MUST use
 * `computeVatSummary` to derive Output VAT, Input VAT (and its components),
 * and Net VAT Payable. No endpoint may compute these figures independently.
 *
 * Canonical formula (ZATCA-aligned, matches Saudi VAT return Box 1..5):
 *
 *   Output VAT       = Σ sales.outputVat
 *   Input VAT (raw)  = Σ purchases.vatAmount
 *   Adjusted Input VAT
 *     = inputVatRaw
 *       − vatTransferredOut            (VAT that left with goods to other branches)
 *       + vatReceivedIn                (VAT that arrived with goods from other branches)
 *       + fixedCostInputVat            (rent, utilities, subscriptions, insurance, …)
 *       + expenseLedgerInputVat        (cleaning, marketing, gov fees, services, …)
 *   Net VAT Payable  = Output VAT − Adjusted Input VAT
 *
 * Exclusion rules (kept consistent across every consumer):
 *   • Fixed-cost templates with category === "staff-salaries" — out of VAT scope
 *   • Expense-ledger rows where isAutoGenerated === true       — already counted at origin
 *   • Branch transfers where toRestaurantId is NULL            — internal consumption, not a transfer
 */
import { db } from "@workspace/db";
import {
  salesTable,
  purchasesTable,
  branchTransfersTable,
  fixedCostTemplatesTable,
  fixedCostMonthlyValuesTable,
  expenseTransactionsTable,
} from "@workspace/db/schema";
import { eq, or, and } from "drizzle-orm";

const toNum = (v: unknown) => parseFloat(String(v)) || 0;
const f2 = (n: number) => +n.toFixed(2);

export type VatSourceRow = {
  sourceType: "purchase" | "fixed-cost" | "expense-ledger" | "transfer-out" | "transfer-in";
  sourceId: string;
  label: string;
  date: string;
  vatType: "none" | "included" | "excluded";
  vatRate: number;
  taxableAmount: number; // net (pre-VAT) base
  vatAmount: number;     // signed: transfer-out is negative on Input VAT
  status: "taxable" | "exempt" | "excluded";
  reason?: string;
};

export type VatExclusionRow = {
  sourceType: "expense-ledger" | "fixed-cost";
  sourceId: string;
  label: string;
  date: string;
  amount: number;
  reason: string;
};

export type VatSummary = {
  filters: { restaurantId: number; month: string | null };

  // ── Output side
  totalSales: number;
  outputVat: number;

  // ── Input side (components)
  totalPurchases: number;        // net (pre-VAT) base from purchase invoices
  inputVatRaw: number;           // VAT from purchase invoices ONLY (pre-adjustment)
  fixedCostInputVat: number;
  fixedCostTaxableNet: number;
  expenseLedgerInputVat: number;
  expenseLedgerNet: number;          // all manual expense rows (incl. exempt)
  expenseLedgerTaxableNet: number;   // only rows that produced input VAT

  // ── Inter-branch transfer VAT allocation
  vatTransferredOut: number;
  vatReceivedIn: number;
  transfersOutCount: number;
  transfersInCount: number;
  netAmountTransferredOut: number;
  netAmountReceivedIn: number;

  // ── Final
  adjustedInputVat: number;
  netVatPayable: number;

  // ── Audit
  totalTaxableExpenses: number;  // purchases + ledger-taxable + fixed-taxable
  breakdown: VatSourceRow[];
  excluded: VatExclusionRow[];

  // ── Debug (helps trace P&L vs VAT Report mismatches)
  debug: {
    formula: string;
    components: Record<string, number>;
  };
};

export type VatSummaryInput = {
  restaurantId: number;
  month?: string | null; // YYYY-MM
};

function computeFixedVatBase(amount: number, vatType: string, vatRate: number) {
  const rate = (vatRate || 15) / 100;
  if (!vatType || vatType === "none" || amount === 0) return { net: amount, vat: 0 };
  if (vatType === "included") {
    const net = amount / (1 + rate);
    return { net, vat: amount - net };
  }
  return { net: amount, vat: amount * rate };
}

/**
 * THE single VAT computation. Every route imports and calls this.
 */
export async function computeVatSummary(input: VatSummaryInput): Promise<VatSummary> {
  const { restaurantId } = input;
  const month = input.month && input.month.length > 0 ? input.month : null;

  // ── Sales & Purchases ──────────────────────────────────────────────────────
  let salesRecords = await db.select().from(salesTable)
    .where(eq(salesTable.restaurantId, restaurantId));
  let purchaseRecords = await db.select().from(purchasesTable)
    .where(eq(purchasesTable.restaurantId, restaurantId));
  if (month) {
    salesRecords    = salesRecords.filter(r => r.date.startsWith(month));
    purchaseRecords = purchaseRecords.filter(r => r.date.startsWith(month));
  }

  const totalSales     = salesRecords.reduce((s, r) => s + toNum(r.totalRevenue), 0);
  const outputVat      = salesRecords.reduce((s, r) => s + toNum(r.outputVat), 0);
  const totalPurchases = purchaseRecords.reduce((s, r) => s + toNum(r.amountBeforeVat), 0);
  const inputVatRaw    = purchaseRecords.reduce((s, r) => s + toNum(r.vatAmount), 0);

  // ── Inter-branch transfers ─────────────────────────────────────────────────
  let allTransfers = await db.select().from(branchTransfersTable)
    .where(or(
      eq(branchTransfersTable.fromRestaurantId, restaurantId),
      eq(branchTransfersTable.toRestaurantId, restaurantId),
    ));
  if (month) allTransfers = allTransfers.filter(t => t.transferDate.startsWith(month));

  // Outbound: ONLY branch-to-branch (toRestaurantId NOT NULL & not self) — internal
  // free-text destinations are consumption, not transfers, and stay in Input VAT.
  const outTransfers = allTransfers.filter(t =>
    t.fromRestaurantId === restaurantId &&
    t.toRestaurantId !== null &&
    t.toRestaurantId !== restaurantId,
  );
  const inTransfers = allTransfers.filter(t => t.toRestaurantId === restaurantId);

  const vatTransferredOut       = outTransfers.reduce((s, t) => s + toNum(t.vatAmount), 0);
  const vatReceivedIn           = inTransfers.reduce((s, t) => s + toNum(t.vatAmount), 0);
  const netAmountTransferredOut = outTransfers.reduce((s, t) => s + toNum(t.quantity) * toNum(t.unitPrice), 0);
  const netAmountReceivedIn     = inTransfers.reduce((s, t) => s + toNum(t.quantity) * toNum(t.unitPrice), 0);

  // ── Expense Ledger (manual rows only — auto-generated are mirrors) ─────────
  let expenseRows = await db.select().from(expenseTransactionsTable)
    .where(eq(expenseTransactionsTable.restaurantId, restaurantId));
  if (month) expenseRows = expenseRows.filter(r => r.month === month);

  const manualExpenses = expenseRows.filter(r => !r.isAutoGenerated);
  const autoExpenses   = expenseRows.filter(r =>  r.isAutoGenerated);

  const expenseLedgerNet        = manualExpenses.reduce((s, r) => s + toNum(r.amount), 0);
  const expenseLedgerInputVat   = manualExpenses.reduce((s, r) => s + toNum(r.vatAmount), 0);
  const expenseLedgerTaxableNet = manualExpenses
    .filter(r => toNum(r.vatAmount) > 0)
    .reduce((s, r) => s + toNum(r.amount), 0);

  // ── Fixed-cost templates ───────────────────────────────────────────────────
  const fcTemplates = await db.select().from(fixedCostTemplatesTable)
    .where(and(
      eq(fixedCostTemplatesTable.restaurantId, restaurantId),
      eq(fixedCostTemplatesTable.isActive, true),
    ));
  // When month is null (all-months), we must aggregate fixed costs over EVERY
  // month that has activity — otherwise a template's recurring monthly amount
  // would only be counted once across the entire history, severely understating
  // input VAT. Months in scope = distinct months present in sales/purchases/
  // expense-ledger/transfers data.
  const fcOverrides = await db.select().from(fixedCostMonthlyValuesTable)
    .where(month
      ? and(
          eq(fixedCostMonthlyValuesTable.restaurantId, restaurantId),
          eq(fixedCostMonthlyValuesTable.month, month),
        )
      : eq(fixedCostMonthlyValuesTable.restaurantId, restaurantId));
  // (templateId, month) → override amount
  const overrideByMonth = new Map<string, number>();
  for (const o of fcOverrides) overrideByMonth.set(`${o.templateId}::${o.month}`, toNum(o.amount));

  const monthsInScope: string[] = month
    ? [month]
    : Array.from(new Set([
        ...salesRecords.map(r => r.date.slice(0, 7)),
        ...purchaseRecords.map(r => r.date.slice(0, 7)),
        ...expenseRows.map(r => r.month),
        ...allTransfers.map(t => t.transferDate.slice(0, 7)),
      ].filter(m => /^\d{4}-\d{2}$/.test(m)))).sort();

  let fixedCostInputVat = 0;
  let fixedCostTaxableNet = 0;
  // Per-template display values (use latest month in scope for the breakdown
  // line so the audit row remains representative — totals are still summed
  // across every month).
  const fcLines: Array<{ template: typeof fcTemplates[number]; net: number; vat: number; eligible: boolean; displayAmount: number }> = [];
  const displayMonth = monthsInScope.length > 0 ? monthsInScope[monthsInScope.length - 1] : (month ?? "");
  for (const t of fcTemplates) {
    const vatType  = (t.vatType ?? "none") as "none" | "included" | "excluded";
    const vatRate  = toNum(t.vatRate ?? "15.00");
    const isSalary = t.category === "staff-salaries";

    let lineNet = 0, lineVat = 0, anyEligible = false;
    let displayAmount = 0;
    for (const m of monthsInScope) {
      const override = overrideByMonth.get(`${t.id}::${m}`);
      const amt = override !== undefined ? override : toNum(t.defaultAmount);
      if (m === displayMonth) displayAmount = amt;
      const eligible = !isSalary && vatType !== "none" && amt > 0;
      if (!eligible) continue;
      const b = computeFixedVatBase(amt, vatType, vatRate);
      lineNet += b.net; lineVat += b.vat; anyEligible = true;
    }
    fixedCostInputVat   += lineVat;
    fixedCostTaxableNet += lineNet;
    fcLines.push({
      template: t,
      net: f2(lineNet),
      vat: f2(lineVat),
      eligible: anyEligible,
      displayAmount,
    });
  }
  fixedCostInputVat   = f2(fixedCostInputVat);
  fixedCostTaxableNet = f2(fixedCostTaxableNet);

  // ── Adjusted Input VAT & Net VAT Payable (THE formula) ────────────────────
  const adjustedInputVat = inputVatRaw
    - vatTransferredOut
    + vatReceivedIn
    + fixedCostInputVat
    + expenseLedgerInputVat;
  const netVatPayable = outputVat - adjustedInputVat;

  const totalTaxableExpenses = totalPurchases + expenseLedgerTaxableNet + fixedCostTaxableNet;

  // ── Breakdown rows (per-source audit) ──────────────────────────────────────
  const breakdown: VatSourceRow[] = [];

  for (const p of purchaseRecords) {
    const vat = toNum(p.vatAmount);
    const net = toNum(p.amountBeforeVat);
    breakdown.push({
      sourceType: "purchase",
      sourceId:   String(p.id),
      label:      `Purchase #${p.id}`,
      date:       p.date,
      vatType:    p.priceIncludesVat ? "included" : (vat > 0 ? "excluded" : "none"),
      vatRate:    net > 0 ? +((vat / net) * 100).toFixed(2) : 0,
      taxableAmount: f2(net),
      vatAmount:     f2(vat),
      status:     vat > 0 ? "taxable" : "exempt",
      reason:     vat > 0 ? undefined : (p.invoiceType === "non-tax" ? "non-tax invoice" : "no VAT recorded"),
    });
  }

  for (const e of manualExpenses) {
    const vat = toNum(e.vatAmount);
    const net = toNum(e.amount);
    breakdown.push({
      sourceType:    "expense-ledger",
      sourceId:      String(e.id),
      label:         `${e.categoryCode} · ${e.description}`,
      date:          e.date,
      vatType:       (e.vatType ?? "none") as "none" | "included" | "excluded",
      vatRate:       toNum(e.vatRate),
      taxableAmount: f2(net),
      vatAmount:     f2(vat),
      status:        vat > 0 ? "taxable" : "exempt",
      reason:        vat > 0 ? undefined : (e.vatType === "none" ? "VAT type: none" : "no VAT recorded"),
    });
  }

  for (const line of fcLines) {
    const { template: t, net, vat, eligible, displayAmount } = line;
    const isSalary = t.category === "staff-salaries";
    const vatType  = (t.vatType ?? "none") as "none" | "included" | "excluded";
    breakdown.push({
      sourceType:    "fixed-cost",
      sourceId:      String(t.id),
      label:         `${t.category} · ${t.name}`,
      date:          month ?? (monthsInScope.length > 0 ? `${monthsInScope[0]} … ${monthsInScope[monthsInScope.length - 1]}` : "—"),
      vatType,
      vatRate:       toNum(t.vatRate ?? "15.00"),
      taxableAmount: net,
      vatAmount:     vat,
      status:        eligible ? "taxable" : (isSalary ? "excluded" : "exempt"),
      reason:        isSalary             ? "category: staff salaries (out of VAT scope)"
                   : vatType === "none"   ? "VAT type: none"
                   : displayAmount === 0  ? "no amount this period"
                   : undefined,
    });
  }

  // Transfer rows (audit visibility — adjustments are already in adjustedInputVat)
  for (const t of outTransfers) {
    breakdown.push({
      sourceType:    "transfer-out",
      sourceId:      String(t.id),
      label:         `Transfer OUT → branch ${t.toRestaurantId} · ${t.itemName ?? ""}`.trim(),
      date:          t.transferDate,
      vatType:       "excluded",
      vatRate:       15,
      taxableAmount: f2(toNum(t.quantity) * toNum(t.unitPrice)),
      vatAmount:     -f2(toNum(t.vatAmount)),
      status:        "taxable",
      reason:        "VAT travels with goods — recovered from this branch's input VAT",
    });
  }
  for (const t of inTransfers) {
    breakdown.push({
      sourceType:    "transfer-in",
      sourceId:      String(t.id),
      label:         `Transfer IN ← branch ${t.fromRestaurantId} · ${t.itemName ?? ""}`.trim(),
      date:          t.transferDate,
      vatType:       "excluded",
      vatRate:       15,
      taxableAmount: f2(toNum(t.quantity) * toNum(t.unitPrice)),
      vatAmount:     f2(toNum(t.vatAmount)),
      status:        "taxable",
      reason:        "VAT travels with goods — added to this branch's input VAT",
    });
  }

  // Sort: source, status, date
  const statusRank = { taxable: 0, exempt: 1, excluded: 2 } as const;
  breakdown.sort((a, b) =>
    a.sourceType.localeCompare(b.sourceType) ||
    statusRank[a.status] - statusRank[b.status] ||
    a.date.localeCompare(b.date),
  );

  // ── Excluded list (audit — intentionally NOT counted) ─────────────────────
  const excluded: VatExclusionRow[] = [
    ...autoExpenses.map(e => ({
      sourceType: "expense-ledger" as const,
      sourceId:   String(e.id),
      label:      `${e.categoryCode} · ${e.description}`,
      date:       e.date,
      amount:     f2(toNum(e.totalAmount)),
      reason:     `auto-generated from ${e.sourceType ?? "source"} (already counted at origin)`,
    })),
    ...fcLines.filter(l => l.template.category === "staff-salaries").map(l => ({
      sourceType: "fixed-cost" as const,
      sourceId:   String(l.template.id),
      label:      `${l.template.category} · ${l.template.name}`,
      date:       month ?? (monthsInScope.length > 0 ? `${monthsInScope[0]} … ${monthsInScope[monthsInScope.length - 1]}` : "—"),
      amount:     f2(l.displayAmount * (month ? 1 : Math.max(1, monthsInScope.length))),
      reason:     "category: staff-salaries (counted via employees/payroll instead)",
    })),
  ];

  return {
    filters: { restaurantId, month },

    totalSales: f2(totalSales),
    outputVat:  f2(outputVat),

    totalPurchases:          f2(totalPurchases),
    inputVatRaw:             f2(inputVatRaw),
    fixedCostInputVat,
    fixedCostTaxableNet,
    expenseLedgerInputVat:   f2(expenseLedgerInputVat),
    expenseLedgerNet:        f2(expenseLedgerNet),
    expenseLedgerTaxableNet: f2(expenseLedgerTaxableNet),

    vatTransferredOut:       f2(vatTransferredOut),
    vatReceivedIn:           f2(vatReceivedIn),
    transfersOutCount:       outTransfers.length,
    transfersInCount:        inTransfers.length,
    netAmountTransferredOut: f2(netAmountTransferredOut),
    netAmountReceivedIn:     f2(netAmountReceivedIn),

    adjustedInputVat: f2(adjustedInputVat),
    netVatPayable:    f2(netVatPayable),

    totalTaxableExpenses: f2(totalTaxableExpenses),
    breakdown,
    excluded,

    debug: {
      formula: "netVatPayable = outputVat − (inputVatRaw − vatTransferredOut + vatReceivedIn + fixedCostInputVat + expenseLedgerInputVat)",
      components: {
        outputVat:             f2(outputVat),
        inputVatRaw:           f2(inputVatRaw),
        minus_vatTransferredOut: f2(-vatTransferredOut),
        plus_vatReceivedIn:    f2(vatReceivedIn),
        plus_fixedCostInputVat: fixedCostInputVat,
        plus_expenseLedgerInputVat: f2(expenseLedgerInputVat),
        equals_adjustedInputVat: f2(adjustedInputVat),
        equals_netVatPayable: f2(netVatPayable),
      },
    },
  };
}
