import { Router, type IRouter } from "express";
import { db } from "@workspace/db";
import {
  salesTable, purchasesTable, employeesTable, expensesTable, branchTransfersTable,
  expenseTransactionsTable, fixedCostTemplatesTable, fixedCostMonthlyValuesTable,
} from "@workspace/db/schema";
import { eq, or, and } from "drizzle-orm";
import { getRestaurantId } from "../lib/restaurant";

const router: IRouter = Router();

function toNum(v: unknown) {
  return parseFloat(String(v));
}

// GET /api/dashboard/summary
router.get("/summary", async (req, res) => {
  try {
    const restaurantId = getRestaurantId(req);
    const month = req.query.month as string | undefined;

    let salesRecords = await db.select().from(salesTable)
      .where(eq(salesTable.restaurantId, restaurantId))
      .orderBy(salesTable.date);
    let purchaseRecords = await db.select().from(purchasesTable)
      .where(eq(purchasesTable.restaurantId, restaurantId))
      .orderBy(purchasesTable.date);

    if (month) {
      salesRecords = salesRecords.filter((r) => r.date.startsWith(month));
      purchaseRecords = purchaseRecords.filter((r) => r.date.startsWith(month));
    }

    const totalNetSales = salesRecords.reduce((s, r) => s + toNum(r.netSales), 0);
    const totalRevenue = salesRecords.reduce((s, r) => s + toNum(r.totalRevenue), 0);
    const outputVat = salesRecords.reduce((s, r) => s + toNum(r.outputVat), 0);
    const totalCash = salesRecords.reduce((s, r) => s + toNum(r.cash), 0);
    const totalCard = salesRecords.reduce((s, r) => s + toNum(r.card), 0);
    const totalApps = salesRecords.reduce((s, r) =>
      s + toNum(r.app1) + toNum(r.app2) + toNum(r.app3) + toNum(r.app4) + toNum(r.app5) + toNum(r.app6), 0);

    const totalPurchases = purchaseRecords.reduce((s, r) => s + toNum(r.amountBeforeVat), 0);
    const inputVat = purchaseRecords.reduce((s, r) => s + toNum(r.vatAmount), 0);
    const vatPayable = outputVat - inputVat;

    const employees = await db.select().from(employeesTable)
      .where(eq(employeesTable.restaurantId, restaurantId));
    const expenses = await db.select().from(expensesTable)
      .where(eq(expensesTable.restaurantId, restaurantId));

    const totalSalaries = employees.reduce((s, e) => s + toNum(e.totalMonthlyCost), 0);
    const totalFixedExpenses = expenses.reduce((s, e) => s + toNum(e.monthlyCost), 0);

    // ── Expense Ledger (manual operating expenses: insurance, gov fees, contracts, …) ──
    // Previously missing — caused dashboard net profit to ignore everything entered
    // through the expense ledger. Auto-generated rows are filtered out to avoid
    // double-counting against their originating source (purchase / payroll / fixed-cost).
    let expenseTxnRows = await db.select().from(expenseTransactionsTable)
      .where(eq(expenseTransactionsTable.restaurantId, restaurantId));
    if (month) expenseTxnRows = expenseTxnRows.filter(r => r.month === month);
    const manualExpenseTxns = expenseTxnRows.filter(r => !r.isAutoGenerated);
    const expenseLedgerNet = manualExpenseTxns.reduce((s, r) => s + toNum(r.amount), 0);
    const expenseLedgerVat = manualExpenseTxns.reduce((s, r) => s + toNum(r.vatAmount), 0);

    // ── Dynamic fixed-cost templates (rent, utilities, subscriptions, …) ──
    // The legacy `expenses` table is largely empty in newer installs; dynamic
    // fixed costs are the source of truth. P&L expenses these on a VAT-exclusive
    // base (computeFixedVat), so we mirror that here to keep dashboard netProfit
    // aligned with /api/reports/pl. Salaries skipped — already in totalSalaries.
    const fcTemplates = await db.select().from(fixedCostTemplatesTable)
      .where(and(
        eq(fixedCostTemplatesTable.restaurantId, restaurantId),
        eq(fixedCostTemplatesTable.isActive, true),
      ));
    const fcOverrides = month
      ? await db.select().from(fixedCostMonthlyValuesTable)
          .where(and(
            eq(fixedCostMonthlyValuesTable.restaurantId, restaurantId),
            eq(fixedCostMonthlyValuesTable.month, month),
          ))
      : [];
    const fcOverrideMap = new Map(fcOverrides.map(o => [o.templateId, toNum(o.amount)]));
    let dynamicFixedCosts = 0;   // VAT-exclusive base (matches P&L)
    let fixedCostInputVat = 0;   // for adjustedInputVat (matches /api/vat/report)
    for (const t of fcTemplates) {
      if (t.category === "staff-salaries") continue;
      const enteredAmt = fcOverrideMap.has(t.id) ? fcOverrideMap.get(t.id)! : toNum(t.defaultAmount);
      const vatType = t.vatType ?? "none";
      const vatRate = (toNum(t.vatRate ?? "15") || 15) / 100;
      let netBase = enteredAmt;
      let vat = 0;
      if (vatType !== "none" && enteredAmt > 0) {
        if (vatType === "included") {
          netBase = enteredAmt / (1 + vatRate);
          vat = enteredAmt - netBase;
        } else { // "excluded"
          netBase = enteredAmt;
          vat = enteredAmt * vatRate;
        }
      }
      dynamicFixedCosts += netBase;
      fixedCostInputVat += vat;
    }

    // ── Inter-branch transfer VAT (mirrors /api/vat/report) ───────────────────
    // VAT that left with goods sent to other branches is recovered; VAT that
    // arrived is added. Branch-to-branch transfers only (toRestaurantId != null).
    let allTransfersVat = await db.select().from(branchTransfersTable)
      .where(or(
        eq(branchTransfersTable.fromRestaurantId, restaurantId),
        eq(branchTransfersTable.toRestaurantId, restaurantId),
      ));
    if (month) allTransfersVat = allTransfersVat.filter(t => t.transferDate.startsWith(month));
    const vatTransferredOut = allTransfersVat
      .filter(t => t.fromRestaurantId === restaurantId && t.toRestaurantId !== null && t.toRestaurantId !== restaurantId)
      .reduce((s, t) => s + toNum(t.vatAmount), 0);
    const vatReceivedIn = allTransfersVat
      .filter(t => t.toRestaurantId === restaurantId)
      .reduce((s, t) => s + toNum(t.vatAmount), 0);

    // ── Internal Branch Transfers — adjust effective purchases ─────────────────
    // Transfers received from other branches = additional internal cost (adds to this branch's effective purchases)
    // Transfers sent to other branches = those goods are no longer this branch's cost (reduces effective purchases)
    // Only branch-to-branch transfers (toRestaurantId IS NOT NULL) are credited back — free-text destinations are consumption
    let allTransfers = await db.select()
      .from(branchTransfersTable)
      .where(or(
        eq(branchTransfersTable.toRestaurantId, restaurantId),
        eq(branchTransfersTable.fromRestaurantId, restaurantId),
      ));

    if (month) {
      allTransfers = allTransfers.filter(t => t.transferDate.startsWith(month));
    }

    const transfersInCost = allTransfers
      .filter(t => t.toRestaurantId === restaurantId)
      .reduce((s, t) => s + toNum(t.quantity) * toNum(t.unitPrice), 0);

    const transfersOutCost = allTransfers
      .filter(t => t.fromRestaurantId === restaurantId && t.toRestaurantId !== null && t.toRestaurantId !== restaurantId)
      .reduce((s, t) => s + toNum(t.quantity) * toNum(t.unitPrice), 0);

    const netTransferCost = transfersInCost - transfersOutCost;
    const effectivePurchases = totalPurchases + netTransferCost;

    // Adjusted input VAT mirrors /api/vat/report exactly:
    //   inputVatRaw - vatTransferredOut + vatReceivedIn + fixedCostVat + expenseLedgerVat
    const adjustedInputVat =
      inputVat - vatTransferredOut + vatReceivedIn + fixedCostInputVat + expenseLedgerVat;
    const adjustedVatPayable = outputVat - adjustedInputVat;

    const netProfit =
      totalNetSales
      - effectivePurchases
      - totalSalaries
      - totalFixedExpenses
      - dynamicFixedCosts
      - expenseLedgerNet
      - adjustedVatPayable;

    res.json({
      month: month ?? "all",
      totalNetSales: +totalNetSales.toFixed(2),
      totalRevenue: +totalRevenue.toFixed(2),
      // Legacy aliases for dashboard compatibility
      totalFoodSales: +totalNetSales.toFixed(2),
      totalBeverageSales: 0,
      totalSales: +totalNetSales.toFixed(2),
      totalCash: +totalCash.toFixed(2),
      totalCard: +totalCard.toFixed(2),
      totalApps: +totalApps.toFixed(2),
      totalPurchases: +totalPurchases.toFixed(2),
      transfersInCost: +transfersInCost.toFixed(2),
      transfersOutCost: +transfersOutCost.toFixed(2),
      netTransferCost: +netTransferCost.toFixed(2),
      effectivePurchases: +effectivePurchases.toFixed(2),
      outputVat: +outputVat.toFixed(2),
      inputVat: +inputVat.toFixed(2),
      vatPayable: +vatPayable.toFixed(2),
      totalSalaries: +totalSalaries.toFixed(2),
      totalFixedExpenses: +(totalFixedExpenses + dynamicFixedCosts).toFixed(2),
      legacyFixedExpenses: +totalFixedExpenses.toFixed(2),
      dynamicFixedCosts: +dynamicFixedCosts.toFixed(2),
      expenseLedgerNet: +expenseLedgerNet.toFixed(2),
      expenseLedgerVat: +expenseLedgerVat.toFixed(2),
      fixedCostInputVat: +fixedCostInputVat.toFixed(2),
      vatTransferredOut: +vatTransferredOut.toFixed(2),
      vatReceivedIn: +vatReceivedIn.toFixed(2),
      adjustedInputVat: +adjustedInputVat.toFixed(2),
      adjustedVatPayable: +adjustedVatPayable.toFixed(2),
      netProfit: +netProfit.toFixed(2),
    });
  } catch (err) {
    req.log.error({ err }, "Error getting dashboard summary");
    res.status(500).json({ error: "Internal server error" });
  }
});

export default router;
