import { Router, type IRouter } from "express";
import { db } from "@workspace/db";
import {
  salesTable, purchasesTable, employeesTable, branchTransfersTable,
  expenseTransactionsTable, fixedCostTemplatesTable, fixedCostMonthlyValuesTable,
} from "@workspace/db/schema";
import { eq, or, and } from "drizzle-orm";
import { getRestaurantId } from "../lib/restaurant";
import { computeVatSummary } from "../lib/vat-engine";

const router: IRouter = Router();

function toNum(v: unknown) {
  return parseFloat(String(v));
}

// GET /api/dashboard/summary
router.get("/summary", async (req, res) => {
  try {
    const restaurantId = getRestaurantId(req);
    const month = req.query.month as string | undefined;

    let salesRecords = await db.select().from(salesTable)
      .where(eq(salesTable.restaurantId, restaurantId))
      .orderBy(salesTable.date);
    let purchaseRecords = await db.select().from(purchasesTable)
      .where(eq(purchasesTable.restaurantId, restaurantId))
      .orderBy(purchasesTable.date);

    if (month) {
      salesRecords = salesRecords.filter((r) => r.date.startsWith(month));
      purchaseRecords = purchaseRecords.filter((r) => r.date.startsWith(month));
    }

    const totalNetSales = salesRecords.reduce((s, r) => s + toNum(r.netSales), 0);
    const totalRevenue = salesRecords.reduce((s, r) => s + toNum(r.totalRevenue), 0);
    const totalCash = salesRecords.reduce((s, r) => s + toNum(r.cash), 0);
    const totalCard = salesRecords.reduce((s, r) => s + toNum(r.card), 0);
    const totalApps = salesRecords.reduce((s, r) =>
      s + toNum(r.app1) + toNum(r.app2) + toNum(r.app3) + toNum(r.app4) + toNum(r.app5) + toNum(r.app6), 0);

    const totalPurchases = purchaseRecords.reduce((s, r) => s + toNum(r.amountBeforeVat), 0);

    const employees = await db.select().from(employeesTable)
      .where(eq(employeesTable.restaurantId, restaurantId));

    const totalSalaries = employees.reduce((s, e) => s + toNum(e.totalMonthlyCost), 0);
    // Legacy `expenses` table is deprecated — all recurring items now live in
    // fixed_cost_templates (single source of truth, Expenses Management module).
    const totalFixedExpenses = 0;

    // ── Expense Ledger (manual rows only — drives netProfit) ──
    let expenseTxnRows = await db.select().from(expenseTransactionsTable)
      .where(eq(expenseTransactionsTable.restaurantId, restaurantId));
    if (month) expenseTxnRows = expenseTxnRows.filter(r => r.month === month);
    const manualExpenseTxns = expenseTxnRows.filter(r => !r.isAutoGenerated);
    const expenseLedgerNet = manualExpenseTxns.reduce((s, r) => s + toNum(r.amount), 0);

    // ── Dynamic fixed costs (VAT-exclusive base for netProfit) ──
    const fcTemplates = await db.select().from(fixedCostTemplatesTable)
      .where(and(
        eq(fixedCostTemplatesTable.restaurantId, restaurantId),
        eq(fixedCostTemplatesTable.isActive, true),
      ));
    const fcOverrides = month
      ? await db.select().from(fixedCostMonthlyValuesTable)
          .where(and(
            eq(fixedCostMonthlyValuesTable.restaurantId, restaurantId),
            eq(fixedCostMonthlyValuesTable.month, month),
          ))
      : [];
    const fcOverrideMap = new Map(fcOverrides.map(o => [o.templateId, toNum(o.amount)]));
    let dynamicFixedCosts = 0;
    for (const t of fcTemplates) {
      if (t.category === "staff-salaries") continue;
      const enteredAmt = fcOverrideMap.has(t.id) ? fcOverrideMap.get(t.id)! : toNum(t.defaultAmount);
      const vatType = t.vatType ?? "none";
      const vatRate = (toNum(t.vatRate ?? "15") || 15) / 100;
      let netBase = enteredAmt;
      if (vatType === "included" && enteredAmt > 0) netBase = enteredAmt / (1 + vatRate);
      dynamicFixedCosts += netBase;
    }

    // ── Branch transfers — affect effective purchases (COGS-side only) ──
    let allTransfers = await db.select()
      .from(branchTransfersTable)
      .where(or(
        eq(branchTransfersTable.toRestaurantId, restaurantId),
        eq(branchTransfersTable.fromRestaurantId, restaurantId),
      ));
    if (month) allTransfers = allTransfers.filter(t => t.transferDate.startsWith(month));

    const transfersInCost = allTransfers
      .filter(t => t.toRestaurantId === restaurantId)
      .reduce((s, t) => s + toNum(t.quantity) * toNum(t.unitPrice), 0);
    const transfersOutCost = allTransfers
      .filter(t => t.fromRestaurantId === restaurantId && t.toRestaurantId !== null && t.toRestaurantId !== restaurantId)
      .reduce((s, t) => s + toNum(t.quantity) * toNum(t.unitPrice), 0);
    const netTransferCost = transfersInCost - transfersOutCost;
    const effectivePurchases = totalPurchases + netTransferCost;

    // ── VAT — UNIFIED via lib/vat-engine (matches /api/vat/report & P&L) ──
    // VAT is a pass-through liability, NOT an expense, so it does NOT affect
    // Net Profit. Net Profit uses VAT-exclusive (Net) totals only. The VAT
    // fields below are exposed informationally so the dashboard can mirror
    // the Zakat & VAT report.
    const vat = await computeVatSummary({ restaurantId, month: month ?? null });
    const adjustedVatPayable = vat.netVatPayable;

    const netProfit =
      totalNetSales
      - effectivePurchases
      - totalSalaries
      - totalFixedExpenses
      - dynamicFixedCosts
      - expenseLedgerNet;

    res.json({
      month: month ?? "all",
      totalNetSales: +totalNetSales.toFixed(2),
      totalRevenue: +totalRevenue.toFixed(2),
      // Legacy aliases
      totalFoodSales: +totalNetSales.toFixed(2),
      totalBeverageSales: 0,
      totalSales: +totalNetSales.toFixed(2),
      totalCash: +totalCash.toFixed(2),
      totalCard: +totalCard.toFixed(2),
      totalApps: +totalApps.toFixed(2),
      totalPurchases: +totalPurchases.toFixed(2),
      transfersInCost: +transfersInCost.toFixed(2),
      transfersOutCost: +transfersOutCost.toFixed(2),
      netTransferCost: +netTransferCost.toFixed(2),
      effectivePurchases: +effectivePurchases.toFixed(2),

      // ── VAT (UNIFIED via lib/vat-engine.ts) ──
      // These MUST match /api/vat/report and /api/reports/pl exactly.
      outputVat:           vat.outputVat,
      inputVat:            vat.inputVatRaw,            // raw purchase VAT (legacy field)
      inputVatRaw:         vat.inputVatRaw,
      vatPayable:          vat.netVatPayable,          // canonical Net VAT Payable
      netVatPayable:       vat.netVatPayable,
      fixedCostInputVat:   vat.fixedCostInputVat,
      expenseLedgerVat:    vat.expenseLedgerInputVat,
      vatTransferredOut:   vat.vatTransferredOut,
      vatReceivedIn:       vat.vatReceivedIn,
      adjustedInputVat:    vat.adjustedInputVat,
      adjustedVatPayable:  vat.netVatPayable,
      vatDebug:            vat.debug,

      totalSalaries: +totalSalaries.toFixed(2),
      totalFixedExpenses: +(totalFixedExpenses + dynamicFixedCosts).toFixed(2),
      legacyFixedExpenses: +totalFixedExpenses.toFixed(2),
      dynamicFixedCosts: +dynamicFixedCosts.toFixed(2),
      expenseLedgerNet: +expenseLedgerNet.toFixed(2),
      netProfit: +netProfit.toFixed(2),
    });
  } catch (err) {
    req.log.error({ err }, "Error getting dashboard summary");
    res.status(500).json({ error: "Internal server error" });
  }
});

export default router;
