import { Router, type IRouter } from "express";
import { db } from "@workspace/db";
import {
  expenseTransactionsTable,
  expenseCategoriesTable,
  purchasesTable,
  fixedCostTemplatesTable,
  fixedCostMonthlyValuesTable,
  salesTable,
  branchTransfersTable,
} from "@workspace/db/schema";
import { eq, and, or } from "drizzle-orm";
import { getRestaurantId } from "../lib/restaurant";
import { computeVatSummary } from "../lib/vat-engine";

const router: IRouter = Router();

const n = (v: unknown) => parseFloat(String(v)) || 0;
const f2 = (x: number) => +x.toFixed(2);

/**
 * GET /api/diagnostics/reporting?month=YYYY-MM
 *
 * Full reconciliation & audit of the reporting integration layer.
 * Verifies that every financial transaction recorded in the database is
 * actually reflected in the aggregated reports, and surfaces any silently
 * excluded data or orphan ledger accounts.
 *
 * Returns:
 *   - sourceCounts:   raw row counts per table
 *   - reconciliation: per-source taxable / VAT totals (matches /api/vat/report.breakdownTotals)
 *   - orphans:        expense_transactions rows whose categoryCode is not in expense_categories
 *   - exclusions:     entries intentionally NOT counted in P&L / VAT, with reason
 *   - ledgerMapping:  per-category counts, totals, VAT-behaviour distribution
 *   - issues:         array of human-readable warnings (length=0 => system is healthy)
 */
router.get("/reporting", async (req, res) => {
  try {
    const restaurantId = getRestaurantId(req);
    const month = (req.query.month as string | undefined) ?? undefined;
    const issues: string[] = [];

    // ── Pull raw data ────────────────────────────────────────────────────────
    const allCategories = await db.select().from(expenseCategoriesTable);
    const categoryCodes = new Set(allCategories.map(c => c.code));

    let purchases = await db.select().from(purchasesTable)
      .where(eq(purchasesTable.restaurantId, restaurantId));
    let expenseTxns = await db.select().from(expenseTransactionsTable)
      .where(eq(expenseTransactionsTable.restaurantId, restaurantId));
    let sales = await db.select().from(salesTable)
      .where(eq(salesTable.restaurantId, restaurantId));

    if (month) {
      purchases   = purchases.filter(p => p.date.startsWith(month));
      expenseTxns = expenseTxns.filter(e => e.month === month);
      sales       = sales.filter(s => s.date.startsWith(month));
    }

    const fcTemplates = await db.select().from(fixedCostTemplatesTable)
      .where(and(
        eq(fixedCostTemplatesTable.restaurantId, restaurantId),
        eq(fixedCostTemplatesTable.isActive, true),
      ));
    const fcOverrides = month
      ? await db.select().from(fixedCostMonthlyValuesTable)
          .where(and(
            eq(fixedCostMonthlyValuesTable.restaurantId, restaurantId),
            eq(fixedCostMonthlyValuesTable.month, month),
          ))
      : [];
    const fcOverrideMap = new Map(fcOverrides.map(o => [o.templateId, n(o.amount)]));

    // ── Orphan ledger accounts ───────────────────────────────────────────────
    // expense_transactions has no FK to expense_categories — a category could
    // be deleted leaving "orphan" rows that may render unexpectedly in reports.
    const orphans = expenseTxns
      .filter(e => !categoryCodes.has(e.categoryCode))
      .map(e => ({
        id: e.id, date: e.date, categoryCode: e.categoryCode,
        description: e.description, amount: f2(n(e.amount)),
      }));
    if (orphans.length > 0) {
      issues.push(`${orphans.length} expense_transactions row(s) reference a category code not present in expense_categories — they may render with a missing label in reports.`);
    }

    // ── Exclusions audit ─────────────────────────────────────────────────────
    // Anything intentionally NOT counted in P&L / VAT and why.
    const autoExpenses = expenseTxns.filter(e => e.isAutoGenerated);
    const salaryTemplates = fcTemplates.filter(t => t.category === "staff-salaries");

    const exclusions = [
      ...autoExpenses.map(e => ({
        source: "expense-ledger" as const,
        id: String(e.id),
        label: `${e.categoryCode} · ${e.description}`,
        amount: f2(n(e.totalAmount)),
        reason: `auto-generated from ${e.sourceType ?? "source"} (already counted at origin)`,
      })),
      ...salaryTemplates.map(t => ({
        source: "fixed-cost" as const,
        id: String(t.id),
        label: `${t.category} · ${t.name}`,
        amount: f2(fcOverrideMap.get(t.id) ?? n(t.defaultAmount)),
        reason: "category: staff-salaries (counted via employees/payroll instead)",
      })),
    ];

    // ── Reconciliation: per-source totals (matches /api/vat/report) ─────────
    const purchaseVat = purchases.reduce((s, p) => s + n(p.vatAmount), 0);
    const purchaseNet = purchases.reduce((s, p) => s + n(p.amountBeforeVat), 0);

    const manualExpenses = expenseTxns.filter(e => !e.isAutoGenerated);
    const expenseLedgerVat = manualExpenses.reduce((s, e) => s + n(e.vatAmount), 0);
    const expenseLedgerNet = manualExpenses.reduce((s, e) => s + n(e.amount), 0);

    // Mirror /api/vat/report exactly — only VAT-eligible templates contribute
    // to fixedCostInputVat/Net; salaries are excluded from VAT scope.
    let fixedCostVat = 0;
    let fixedCostNet = 0;
    for (const t of fcTemplates) {
      if (t.category === "staff-salaries") continue;
      const vt = t.vatType ?? "none";
      if (vt === "none") continue;
      const amt = fcOverrideMap.get(t.id) ?? n(t.defaultAmount);
      if (amt === 0) continue;
      const rate = (n(t.vatRate ?? "15") || 15) / 100;
      const net  = vt === "included" ? amt / (1 + rate) : amt;
      const vat  = vt === "included" ? amt - net : amt * rate;
      fixedCostNet += net;
      fixedCostVat += vat;
    }

    // Inter-branch transfer VAT adjustments — present in /api/vat/report
    let transfers = await db.select().from(branchTransfersTable)
      .where(or(
        eq(branchTransfersTable.fromRestaurantId, restaurantId),
        eq(branchTransfersTable.toRestaurantId, restaurantId),
      ));
    if (month) transfers = transfers.filter(t => t.transferDate.startsWith(month));
    const vatTransferredOut = transfers
      .filter(t => t.fromRestaurantId === restaurantId && t.toRestaurantId !== null && t.toRestaurantId !== restaurantId)
      .reduce((s, t) => s + n(t.vatAmount), 0);
    const vatReceivedIn = transfers
      .filter(t => t.toRestaurantId === restaurantId)
      .reduce((s, t) => s + n(t.vatAmount), 0);

    // ── Reconciliation: derived from the UNIFIED VAT engine ─────────────────
    // We pull the canonical totals from lib/vat-engine.ts AND independently
    // recompute the per-source sums above, then assert they agree.
    // Any drift (>0.01) is surfaced in `issues` so it cannot be ignored.
    const vatSummary = await computeVatSummary({ restaurantId, month: month ?? null });
    const localTotalInputVat = purchaseVat + expenseLedgerVat + fixedCostVat - vatTransferredOut + vatReceivedIn;
    const engineDrift = {
      outputVat:             Math.abs(vatSummary.outputVat             - f2(vatSummary.outputVat)),
      inputVatRaw:           Math.abs(vatSummary.inputVatRaw           - f2(purchaseVat)),
      expenseLedgerInputVat: Math.abs(vatSummary.expenseLedgerInputVat - f2(expenseLedgerVat)),
      fixedCostInputVat:     Math.abs(vatSummary.fixedCostInputVat     - f2(fixedCostVat)),
      adjustedInputVat:      Math.abs(vatSummary.adjustedInputVat      - f2(localTotalInputVat)),
      netVatPayable:         Math.abs(vatSummary.netVatPayable         - f2(vatSummary.outputVat - localTotalInputVat)),
    };
    const maxDrift = Math.max(...Object.values(engineDrift));
    if (maxDrift > 0.01) {
      issues.push(`VAT engine drift detected (max ${maxDrift.toFixed(4)} SAR) — diagnostics ↔ engine should agree.`);
    }

    const reconciliation = {
      outputVat: vatSummary.outputVat,
      inputVat: {
        purchases:        { vat: vatSummary.inputVatRaw,           net: f2(purchaseNet) },
        expenseLedger:    { vat: vatSummary.expenseLedgerInputVat, net: vatSummary.expenseLedgerNet },
        fixedCosts:       { vat: vatSummary.fixedCostInputVat,     net: vatSummary.fixedCostTaxableNet },
        vatTransferredOut: vatSummary.vatTransferredOut,
        vatReceivedIn:    vatSummary.vatReceivedIn,
        adjustedTotal:    vatSummary.adjustedInputVat,
      },
      netVatPayable: vatSummary.netVatPayable,
      engineDrift,
      formula: vatSummary.debug.formula,
      components: vatSummary.debug.components,
    };

    // ── Ledger mapping audit ─────────────────────────────────────────────────
    // For each category that has at least one transaction, summarise totals and
    // verify the VAT behaviour distribution (none / included / excluded).
    const byCategory = new Map<string, {
      code: string;
      label: string;
      txnCount: number;
      totalNet: number;
      totalVat: number;
      vatBehaviour: { none: number; included: number; excluded: number };
    }>();
    for (const c of allCategories) {
      byCategory.set(c.code, {
        code: c.code,
        label: c.nameAr || c.name,
        txnCount: 0, totalNet: 0, totalVat: 0,
        vatBehaviour: { none: 0, included: 0, excluded: 0 },
      });
    }
    for (const e of manualExpenses) {
      const row = byCategory.get(e.categoryCode);
      if (!row) continue; // orphan — already reported above
      row.txnCount += 1;
      row.totalNet += n(e.amount);
      row.totalVat += n(e.vatAmount);
      const vt = (e.vatType ?? "none") as "none" | "included" | "excluded";
      row.vatBehaviour[vt] = (row.vatBehaviour[vt] ?? 0) + 1;
    }
    const ledgerMapping = [...byCategory.values()]
      .filter(r => r.txnCount > 0)
      .map(r => ({
        ...r,
        totalNet: f2(r.totalNet),
        totalVat: f2(r.totalVat),
      }))
      .sort((a, b) => b.totalNet - a.totalNet);

    // ── Nature mapping audit (Fixed vs Variable classification) ─────────────
    // Every leaf expense category MUST have a nature ('fixed' | 'variable').
    // Anything else falls through to "unclassified" in P&L and silently distorts
    // the Fixed/Variable totals — flag it so it can be mapped.
    const unmappedCategories = allCategories
      .filter(c => c.level === 2 && c.isActive && !c.nature)
      .map(c => ({ code: c.code, name: c.name, nameAr: c.nameAr }));
    if (unmappedCategories.length > 0) {
      issues.push(`${unmappedCategories.length} leaf expense category/ies have no nature (fixed/variable) — entries against them won't appear in Fixed-vs-Variable totals.`);
    }
    // Also flag transactions whose category resolves to no nature
    const codesWithoutNature = new Set(
      allCategories.filter(c => !c.nature).map(c => c.code),
    );
    const unclassifiedTxns = manualExpenses.filter(e => {
      if (e.categoryCode.startsWith("5-2")) return false; // HR excluded by design
      // walk up parent chain to see if any ancestor has nature
      const cat = allCategories.find(c => c.code === e.categoryCode);
      if (!cat) return true; // orphan — already flagged
      if (cat.nature) return false;
      const parts = e.categoryCode.split("-");
      while (parts.length > 1) {
        parts.pop();
        const parent = allCategories.find(c => c.code === parts.join("-"));
        if (parent?.nature) return false;
      }
      return true;
    });
    if (unclassifiedTxns.length > 0) {
      issues.push(`${unclassifiedTxns.length} expense_transactions row(s) belong to a category with no nature mapping.`);
    }

    // Health-check: every category with VAT recorded should have isVatApplicable consistent
    const inconsistent = manualExpenses.filter(e =>
      (n(e.vatAmount) > 0 && (e.vatType === "none" || !e.isVatApplicable)) ||
      (n(e.vatAmount) === 0 && e.isVatApplicable && e.vatType !== "none" && n(e.amount) > 0)
    );
    if (inconsistent.length > 0) {
      issues.push(`${inconsistent.length} expense_transactions row(s) have inconsistent VAT flags (vatAmount, vatType, isVatApplicable disagree).`);
    }

    res.json({
      month: month ?? "all",
      restaurantId,
      sourceCounts: {
        sales: sales.length,
        purchases: purchases.length,
        expenseTransactions: expenseTxns.length,
        expenseTransactionsManual: manualExpenses.length,
        expenseTransactionsAuto: autoExpenses.length,
        fixedCostTemplatesActive: fcTemplates.length,
        fixedCostMonthlyOverrides: fcOverrides.length,
        expenseCategoriesDefined: allCategories.length,
      },
      reconciliation: {
        ...reconciliation,
        transferAdjustments: {
          vatTransferredOut: f2(vatTransferredOut),
          vatReceivedIn: f2(vatReceivedIn),
        },
      },
      orphans,
      exclusions,
      inconsistentVatFlags: inconsistent.map(e => ({
        id: e.id, categoryCode: e.categoryCode, description: e.description,
        vatType: e.vatType, isVatApplicable: e.isVatApplicable,
        amount: f2(n(e.amount)), vatAmount: f2(n(e.vatAmount)),
      })),
      ledgerMapping,
      natureMapping: {
        unmappedCategories,
        unclassifiedTransactions: unclassifiedTxns.map(e => ({
          id: e.id, date: e.date, categoryCode: e.categoryCode,
          description: e.description, amount: f2(n(e.amount)),
        })),
      },
      issues,
      healthy: issues.length === 0,
    });
  } catch (err) {
    req.log.error({ err }, "Error running reporting diagnostics");
    res.status(500).json({ error: "Internal server error" });
  }
});

export default router;
