/**
 * Expense Integration Routes
 * POST /api/expense-integrations/sync-payroll     — mirrors all employees as expense entries for a month
 * POST /api/expense-integrations/sync-fixed-costs — mirrors fixed-cost templates as expense entries
 * GET  /api/expense-integrations/status           — shows sync counts per source for a month
 */
import { Router, type IRouter } from "express";
import { db } from "@workspace/db";
import {
  employeesTable,
  fixedCostTemplatesTable,
  fixedCostMonthlyValuesTable,
  expenseTransactionsTable,
} from "@workspace/db/schema";
import { eq, and } from "drizzle-orm";
import { getRestaurantId } from "../lib/restaurant";
import {
  upsertExpenseFromEmployee,
  upsertExpenseFromFixedCost,
  deleteExpenseBySourceId,
  sourceId,
} from "../lib/expense-integration";

const router: IRouter = Router();
function toNum(v: unknown) { return parseFloat(String(v)) || 0; }

// ─── GET /api/expense-integrations/status ────────────────────────────────────
router.get("/status", async (req, res) => {
  try {
    const restaurantId = getRestaurantId(req);
    const month = (req.query.month as string) || new Date().toISOString().substring(0, 7);

    const expTxns = await db.select({
      sourceType: expenseTransactionsTable.sourceType,
      sourceId:   expenseTransactionsTable.sourceId,
    })
      .from(expenseTransactionsTable)
      .where(and(
        eq(expenseTransactionsTable.restaurantId, restaurantId),
        eq(expenseTransactionsTable.month, month),
        eq(expenseTransactionsTable.isAutoGenerated, true),
      ));

    const purchaseCount   = expTxns.filter(t => t.sourceType === "purchase").length;
    const payrollCount    = expTxns.filter(t => t.sourceType === "payroll").length;
    const fixedCostCount  = expTxns.filter(t => t.sourceType === "fixed-cost").length;

    const [employeeCount] = await db.select({ count: employeesTable.id })
      .from(employeesTable)
      .where(eq(employeesTable.restaurantId, restaurantId));

    const fcTemplates = await db.select()
      .from(fixedCostTemplatesTable)
      .where(and(
        eq(fixedCostTemplatesTable.restaurantId, restaurantId),
        eq(fixedCostTemplatesTable.isActive, true),
      ));

    res.json({
      month,
      purchases:   { synced: purchaseCount },
      payroll:     { synced: payrollCount,   total: (employeeCount as unknown as typeof employeesTable.$inferSelect[])?.length ?? 0 },
      fixedCosts:  { synced: fixedCostCount, total: fcTemplates.length },
    });
  } catch (err) {
    req.log.error({ err }, "Error fetching integration status");
    res.status(500).json({ error: "Internal server error" });
  }
});

// ─── POST /api/expense-integrations/sync-payroll ─────────────────────────────
router.post("/sync-payroll", async (req, res) => {
  try {
    const restaurantId = getRestaurantId(req);
    const month = (req.query.month as string) || (req.body.month as string);
    if (!month) return res.status(400).json({ error: "month is required (YYYY-MM)" });

    const employees = await db.select().from(employeesTable)
      .where(eq(employeesTable.restaurantId, restaurantId));

    let synced = 0;
    for (const emp of employees) {
      await upsertExpenseFromEmployee(restaurantId, month, {
        id:         emp.id,
        name:       emp.name,
        salary:     toNum(emp.salary),
        overtime:   toNum(emp.overtime),
        deductions: toNum(emp.deductions),
        absences:   toNum(emp.absences),
      });
      synced++;
    }

    res.json({ success: true, month, synced, message: `تم ترحيل ${synced} راتب إلى دفتر المصروفات` });
  } catch (err) {
    req.log.error({ err }, "Error syncing payroll");
    res.status(500).json({ error: "Internal server error" });
  }
});

// ─── POST /api/expense-integrations/sync-fixed-costs ─────────────────────────
router.post("/sync-fixed-costs", async (req, res) => {
  try {
    const restaurantId = getRestaurantId(req);
    const month = (req.query.month as string) || (req.body.month as string);
    if (!month) return res.status(400).json({ error: "month is required (YYYY-MM)" });

    const templates = await db.select()
      .from(fixedCostTemplatesTable)
      .where(and(
        eq(fixedCostTemplatesTable.restaurantId, restaurantId),
        eq(fixedCostTemplatesTable.isActive, true),
      ));

    const overrides = await db.select()
      .from(fixedCostMonthlyValuesTable)
      .where(and(
        eq(fixedCostMonthlyValuesTable.restaurantId, restaurantId),
        eq(fixedCostMonthlyValuesTable.month, month),
      ));

    const overrideMap = new Map(overrides.map(o => [o.templateId, toNum(o.amount)]));

    let synced = 0;
    for (const t of templates) {
      const amount = overrideMap.has(t.id) ? overrideMap.get(t.id)! : toNum(t.defaultAmount);
      if (amount <= 0) continue;
      await upsertExpenseFromFixedCost(restaurantId, month, {
        id:       t.id,
        category: t.category,
        name:     t.name,
        amount,
      });
      synced++;
    }

    res.json({ success: true, month, synced, message: `تم ترحيل ${synced} مصروف ثابت إلى دفتر المصروفات` });
  } catch (err) {
    req.log.error({ err }, "Error syncing fixed costs");
    res.status(500).json({ error: "Internal server error" });
  }
});

// ─── POST /api/expense-integrations/clear-auto ───────────────────────────────
// Remove all auto-generated entries for a month + sourceType (for re-sync)
router.post("/clear-auto", async (req, res) => {
  try {
    const restaurantId = getRestaurantId(req);
    const { month, sourceType } = req.body;
    if (!month) return res.status(400).json({ error: "month is required" });

    let query = db.delete(expenseTransactionsTable).where(
      and(
        eq(expenseTransactionsTable.restaurantId, restaurantId),
        eq(expenseTransactionsTable.month, month),
        eq(expenseTransactionsTable.isAutoGenerated, true),
        sourceType ? eq(expenseTransactionsTable.sourceType, sourceType) : undefined,
      )
    );
    await query;
    res.json({ success: true });
  } catch (err) {
    req.log.error({ err }, "Error clearing auto entries");
    res.status(500).json({ error: "Internal server error" });
  }
});

export default router;
